default: &default
  adapter: postgresql
  encoding: unicode
  host: pg-docker
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: postgres_development

test:
  <<: *default
  database: postgres_test

production:
  <<: *default
  database: postgres_production
